### ISSUE TITLE
2) MVP List

### ISSUE THREAD

**Issue by cdellacqua123** [matthewlese/Mediyum#2]
- [x] Should have 7 MVPs.
    - [x] 3 of those are User Auth, Heroku, and Production README.
    - [x] The other 4 are from the [MVP List](https://open.appacademy.io/learn/swe-campus-hybrid/full-stack-project/mvp-checklist) or they have clarified them with you
- [x] Includes two to three detailed bullets on functionality and presentation of feature
- [x] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [x] Estimates how long it will take the code each MVP
- [x] Correctly formatted
    - [x] MVPs are listed in an ordered list
    - [x] Each MVP is broken down into bullet points

**Comment by cdellacqua123** [comment]
Great job!

**Comment by idiomattic** [comment]
Thanks for the feedback, Chris.  I made the changes to my wiki home page to
satisfy all of the requirements.
