### ISSUE TITLE
3) Database Schema

### ISSUE THREAD

**Issue by cdellacqua123** [matthewlese/Mediyum#3]
- [x] Contains correct datatypes
- [x] Contains appropriate constraints/details (primary and foreign keys, not null, indexed, unique)
- [x] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
- [x] Correctly formatted
    - [x] schema is written in a table format
    - [x] table names, column names, and foreign keys are lowercased, snake_cased and `back_ticked`
    - [x] the table header column names are bolded

**Comment by cdellacqua123** [comment]
Great job! You're really close on this one! Here's what I saw:

- Double check formatting, the table headers should be bold (I also like to make them h2's to be a little easier to read, can do that by adding `##` before the title
- Missing the bullet points after each table explaining what the columns of the table are referencing (take a look at the Blue Bird schema to see what sort of information should be there)
- I noticed there's not a `null: false` constraint for `comment_id` in the `claps` table. Is this because people can clap stories rather than comments? If so, great! Just make sure to mention that in your bullet points below.

**Comment by idiomattic** [comment]
Thanks for your comments!  I made the formatting corrections and added info for my planned associations.
On your last point, re: null: false on comment_id - that was indeed the reason why I left off the constraint.  A clap will always be under a story, but not necessarily under a comment.

**Comment by cdellacqua123** [comment]
Great! Yeah just make sure to back-tick the column names you have in parentheses ((through author_id) should be (through `author_id`)) and you'll be good to go! Feel free to close this issue once you've done that
